// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YurtYonetimSistemi.API.Models;

#nullable disable

namespace YurtYonetimSistemi.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250505191927_AddKartUIDToKullanici")]
    partial class AddKartUIDToKullanici
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Anket", b =>
                {
                    b.Property<Guid>("AnketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Soru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnketID");

                    b.ToTable("Anketler");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.AnketCevap", b =>
                {
                    b.Property<Guid>("CevapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnketID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Puan")
                        .HasColumnType("int");

                    b.HasKey("CevapID");

                    b.HasIndex("AnketID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("AnketCevaplar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.BakimTalep", b =>
                {
                    b.Property<Guid>("TalepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TalepDurumu")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TalepTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("TalepID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("BakimTalepleri");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Basvuru", b =>
                {
                    b.Property<Guid>("BasvuruID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdliSicilBelgesiPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BasvuruKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BasvuruTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Bolum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OgrenciBelgesiPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Okul")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Sinif")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BasvuruID");

                    b.ToTable("Basvurular");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.CamasirhanePlani", b =>
                {
                    b.Property<Guid>("PlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OdaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SaatAraligi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlanID");

                    b.HasIndex("OdaID");

                    b.ToTable("CamasirhanePlani");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Etkinlik", b =>
                {
                    b.Property<Guid>("EtkinlikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("Kontenjan")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("EtkinlikID");

                    b.ToTable("Etkinlikler");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.EtkinlikKatilim", b =>
                {
                    b.Property<Guid>("KatilimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EtkinlikID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KatilimID");

                    b.HasIndex("EtkinlikID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("EtkinlikKatilimlari");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.GirisCikis", b =>
                {
                    b.Property<Guid>("GirisCikisID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("GirisMi")
                        .HasColumnType("bit");

                    b.Property<Guid>("KullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ZamanDamgasi")
                        .HasColumnType("datetime2");

                    b.HasKey("GirisCikisID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("GirisCikislar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Kullanici", b =>
                {
                    b.Property<Guid>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KartUID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OdaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RolID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SinifID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.HasIndex("OdaID");

                    b.HasIndex("RolID");

                    b.HasIndex("SinifID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.KutuphaneKatilim", b =>
                {
                    b.Property<Guid>("KatilimID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KutuphanePlanID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("KatilimID");

                    b.HasIndex("KullaniciID");

                    b.HasIndex("KutuphanePlanID");

                    b.ToTable("KutuphaneKatilimlar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.KutuphanePlani", b =>
                {
                    b.Property<Guid>("KutuphanePlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<string>("Gun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KutuphaneSubeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SaatAraligi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("KutuphanePlanID");

                    b.HasIndex("KutuphaneSubeID");

                    b.ToTable("KutuphanePlanlari");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.KutuphaneSubesi", b =>
                {
                    b.Property<Guid>("KutuphaneSubeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.HasKey("KutuphaneSubeID");

                    b.ToTable("KutuphaneSubeleri");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Oda", b =>
                {
                    b.Property<Guid>("OdaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<int>("KatNo")
                        .HasColumnType("int");

                    b.Property<string>("OdaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OdaID");

                    b.ToTable("Odalar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Odeme", b =>
                {
                    b.Property<Guid>("OdemeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KullaniciID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SonOdemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OdemeID");

                    b.HasIndex("KullaniciID");

                    b.ToTable("Odemeler");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Rol", b =>
                {
                    b.Property<Guid>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RolAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolID");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.RolYetki", b =>
                {
                    b.Property<Guid>("RolYetkiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("YetkiID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolYetkiID");

                    b.HasIndex("RolID");

                    b.HasIndex("YetkiID");

                    b.ToTable("RolYetkiler");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Sinif", b =>
                {
                    b.Property<Guid>("SinifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<int>("KatNo")
                        .HasColumnType("int");

                    b.Property<string>("SinifAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SinifID");

                    b.ToTable("Siniflar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.YemekhaneMenusu", b =>
                {
                    b.Property<Guid>("MenuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ogun")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<string>("Yemekler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuID");

                    b.ToTable("YemekhaneMenusu");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Yetki", b =>
                {
                    b.Property<Guid>("YetkiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("YetkiAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YetkiID");

                    b.ToTable("Yetkiler");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.AnketCevap", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Anket", "Anket")
                        .WithMany("Cevaplar")
                        .HasForeignKey("AnketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YurtYonetimSistemi.API.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anket");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.BakimTalep", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.CamasirhanePlani", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Oda", "Oda")
                        .WithMany()
                        .HasForeignKey("OdaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oda");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.EtkinlikKatilim", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Etkinlik", "Etkinlik")
                        .WithMany("Katilimlar")
                        .HasForeignKey("EtkinlikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YurtYonetimSistemi.API.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Etkinlik");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.GirisCikis", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Kullanici", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Oda", "Oda")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("OdaID");

                    b.HasOne("YurtYonetimSistemi.API.Models.Rol", "Rol")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("RolID");

                    b.HasOne("YurtYonetimSistemi.API.Models.Sinif", "Sinif")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("SinifID");

                    b.Navigation("Oda");

                    b.Navigation("Rol");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.KutuphaneKatilim", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YurtYonetimSistemi.API.Models.KutuphanePlani", "Plan")
                        .WithMany("Katilimlar")
                        .HasForeignKey("KutuphanePlanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.KutuphanePlani", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.KutuphaneSubesi", "KutuphaneSubesi")
                        .WithMany("Planlar")
                        .HasForeignKey("KutuphaneSubeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KutuphaneSubesi");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Odeme", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.RolYetki", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Rol", "Rol")
                        .WithMany("RolYetkiler")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YurtYonetimSistemi.API.Models.Yetki", "Yetki")
                        .WithMany("RolYetkiler")
                        .HasForeignKey("YetkiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Anket", b =>
                {
                    b.Navigation("Cevaplar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Etkinlik", b =>
                {
                    b.Navigation("Katilimlar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.KutuphanePlani", b =>
                {
                    b.Navigation("Katilimlar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.KutuphaneSubesi", b =>
                {
                    b.Navigation("Planlar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Oda", b =>
                {
                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Rol", b =>
                {
                    b.Navigation("Kullanicilar");

                    b.Navigation("RolYetkiler");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Sinif", b =>
                {
                    b.Navigation("Kullanicilar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Yetki", b =>
                {
                    b.Navigation("RolYetkiler");
                });
#pragma warning restore 612, 618
        }
    }
}
