// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YurtYonetimSistemi.API.Models;

#nullable disable

namespace YurtYonetimSistemi.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250401191605_OgrenciOdaSinifIliski")]
    partial class OgrenciOdaSinifIliski
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Kullanici", b =>
                {
                    b.Property<int>("KullaniciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciID"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciID");

                    b.HasIndex("RolID");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Oda", b =>
                {
                    b.Property<Guid>("OdaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<int>("KatNo")
                        .HasColumnType("int");

                    b.Property<string>("OdaNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SinifID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OdaID");

                    b.HasIndex("SinifID");

                    b.ToTable("Odalar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Ogrenci", b =>
                {
                    b.Property<Guid>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OdaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SinifID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OgrenciID");

                    b.HasIndex("OdaID");

                    b.HasIndex("SinifID");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Rol", b =>
                {
                    b.Property<Guid>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RolAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolID");

                    b.ToTable("Roller");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.RolYetki", b =>
                {
                    b.Property<Guid>("RolYetkiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("YetkiID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RolYetkiID");

                    b.HasIndex("RolID");

                    b.HasIndex("YetkiID");

                    b.ToTable("RolYetkiler");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Sinif", b =>
                {
                    b.Property<Guid>("SinifID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<int>("KatNo")
                        .HasColumnType("int");

                    b.Property<string>("SinifAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SinifID");

                    b.ToTable("Siniflar");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Yetki", b =>
                {
                    b.Property<Guid>("YetkiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("YetkiAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("YetkiID");

                    b.ToTable("Yetkiler");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Kullanici", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Rol", "Rol")
                        .WithMany("Kullanicilar")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Oda", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Sinif", "Sinif")
                        .WithMany()
                        .HasForeignKey("SinifID");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Ogrenci", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Oda", "Oda")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("OdaID");

                    b.HasOne("YurtYonetimSistemi.API.Models.Sinif", "Sinif")
                        .WithMany("Ogrenciler")
                        .HasForeignKey("SinifID");

                    b.Navigation("Oda");

                    b.Navigation("Sinif");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.RolYetki", b =>
                {
                    b.HasOne("YurtYonetimSistemi.API.Models.Rol", "Rol")
                        .WithMany("RolYetkiler")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YurtYonetimSistemi.API.Models.Yetki", "Yetki")
                        .WithMany("RolYetkiler")
                        .HasForeignKey("YetkiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Yetki");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Oda", b =>
                {
                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Rol", b =>
                {
                    b.Navigation("Kullanicilar");

                    b.Navigation("RolYetkiler");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Sinif", b =>
                {
                    b.Navigation("Ogrenciler");
                });

            modelBuilder.Entity("YurtYonetimSistemi.API.Models.Yetki", b =>
                {
                    b.Navigation("RolYetkiler");
                });
#pragma warning restore 612, 618
        }
    }
}
